version: "3.8"

services:
  jupyter:
    build: .
    container_name: python_env
    ports:
      - "4222:4222"        # Map host:container port for Jupyter
    volumes:
      - /home/ubuntu:/home/ubuntu
    stdin_open: true       # Keep STDIN open so you can attach later
    tty: true              # Allocate a pseudo-TTY for bash
